version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hkbp_webserver
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root_password}
      - DB_NAME=${DB_NAME:-db_admin}

  db:
    image: mysql:8.0
    container_name: hkbp_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_NAME:-db_admin}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
    driver: local
