version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hkbp_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=db_admin
      - DB_PORT=3306
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db
    networks:
      - hkbp_network

  db:
    image: mysql:8.0
    container_name: hkbp_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=db_admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - SERVICE_NAME=mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - hkbp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hkbp_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=
    depends_on:
      - db
    networks:
      - hkbp_network

networks:
  hkbp_network:
    driver: bridge

volumes:
  dbdata:
